/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _font_metrics_h_
#define _font_metrics_h_
//---------------------------------------------------------------------------------
extern const unsigned char font_metrics[];
extern const int font_metrics_size;
//---------------------------------------------------------------------------------
#endif //_font_metrics_h_
//---------------------------------------------------------------------------------
