/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _libwiisprite_h_
#define _libwiisprite_h_
//---------------------------------------------------------------------------------
extern const unsigned char libwiisprite[];
extern const int libwiisprite_size;
//---------------------------------------------------------------------------------
#endif //_libwiisprite_h_
//---------------------------------------------------------------------------------
